### ISSUE TITLE
New release 2.0?

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#121]
Will you release a new Version, or do you have more refactoring plans before the release?

**Comment by dadhi** [comment]
I want to finish tests for LE.Expression.

**Comment by jogibear9988** [comment]
As now all tests are finished, and all work. Time for new Release?

**Comment by jogibear9988** [comment]
or maybe we fix #81 before? I think c#7.3 should be possible?

**Comment by jogibear9988** [comment]
maybe project icon should also be selected before!

**Comment by dadhi** [comment]
> or maybe we fix #81 before? I think c#7.3 should be possible?

I think it will be to much.

For 2.0 I want too:

- Uncomment code in benchmarks
- Probably run the ones from readme and update results
- Update readme with details for FEC.LE

**Comment by dadhi** [comment]
I would love to see help for #123. Here if will #81 would help we may consider to go to C#7.3 earlier.

**Comment by jogibear9988** [comment]
don't know if I could help with #123 

how would you analyze?

**Comment by dadhi** [comment]
I mean that perf gains would be fractional without digging into CreateDelegate or parallelizing, or something. But the memory in G1 and G2 is k8nda bad in the long run.

**Comment by jogibear9988** [comment]
yes, but how to analyse the memory?

**Comment by dadhi** [comment]
I will be wrapping the work on V2 on this weekend: writing release notes and updating readme. If someone still wants to include something breaking, there is a last chance :) Otherwise let's move on.

**Comment by jogibear9988** [comment]
linq2db still has failing tests i like to fix

**Comment by jogibear9988** [comment]
we also introduced some new i‘d look

**Comment by dadhi** [comment]
Ok. I can wait.

**Comment by dadhi** [comment]
Looking at all these `parent`, `ignoreResult`, `isMemberAccess` combinations. They look ad-hoc and not-reliable. 

I sm thinking about a ways to simplify them w/out full stack.

What if I add enum flags and consolidate bool options into them. Flags are also extensible. May be I will find a pattern in the process.

**Comment by dadhi** [comment]
Here is v2.0 release notes draft: https://github.com/dadhi/FastExpressionCompiler/releases/edit/untagged-ecdd6a8ec38e004746af

Posting it here to decide what else except the fixes list could be added.

**Comment by jogibear9988** [comment]
I still have 3 Tests in linq2db wich do not work (Invalid Program Exception). Hopefully I'll get them fixed before the release

**Comment by jogibear9988** [comment]
the link is not reachable

**Comment by dadhi** [comment]
Hmm, may be because it is s draft. Will insert here...

---

## Major release

Contains a breaking changes, but
**likely or lucky you'll need to re-compile only**.

### The main change 

FEC package split into two: [FastExpressionCompiler (FEC)] and [FastExpressionCompiler.LightExpression (FEC.LE)]. The packages are not dependent on each other and may be used together. 

FEC.LightExpression allows a drop-in replacenent for manually created expression, the only change is different namespace using. LE.Expression is lighter - faster created and less memory consumed in a process, because it does not do all compatibility and verification checks. __But it does not mean it is no safe!__ You can convert it to System Expression as easy as calling `ToExpression` or `ToLambdaExpression` and it will run the usual verification. This conversation also enables fallback to `Expression.Compile` inside the `CompileFast`.

- `ExpressionInfo` and supporting logic is moved from FEC to FEC.LE
- `ExpressionInfo` is renamed to `Expression` but moved into new namespace `FastExpressionCompiler.LightExpression`
- _FastExpressionCompiler.cs_ stripped from `ExpressionInfo` noise and now is much simpler and lost 33% LOC.
- _FastExpressionCompiler.cs_ is shared between FEC and FEC.LE with `LIGHT_EXPRESSION` build variable controlling what to compile: `System.Linq.Expressions.Expression` or `FastExpressionCompiler.LightExpression`

### Fixes

- [TODO]

**Comment by dadhi** [comment]
Published table 2.0.
