### ISSUE TITLE
Linq2db - Test for JIT compiler internal limitation

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#131]
This code also shows the problem

            var body = Block(
                typeof(int),
                new[] { varClass2 }, //, varClass3, varClass4 },
                Assign(varClass2, Field(Convert(objParam, typeof(TestClass1)), nameof(TestClass1.Class2))),
                IfThen(
                    Equal(varClass2, Constant(null)),
                    Block(
                        Assign(varClass2, New(typeof(TestClass2))),
                        Assign(Field(Convert(objParam, typeof(TestClass1)), nameof(TestClass1.Class2)), varClass2))),
                Constant(1)

The Problem is, in the TryEmitAssign, shouldPushResult get's true, because it's the ResultExpr. of the current block, but the result should not be pushed.

@dadhi any good idea how we could fix this?

**Comment by jogibear9988** [comment]
We need to set (when we create a new BlockInfo) if the Child Block is used in a Assignment or as Last Value in the Container Block

**Comment by dadhi** [comment]
No idea, until I got to laptop. Which is Tomorrow.

**Comment by jogibear9988** [comment]
I think, in some way, every child expression needs to know if the parent should return a Value

**Comment by jogibear9988** [comment]
Have you got time to think about this? In the upper Code, the last Assign needs to know, it is not allowed to return a Value

**Comment by dadhi** [comment]
Mmm, I have probably answered in the another issue, cannot find it now.

I think we may path more info as a `parent` parameter instead of just a `ExpressionType`. We may pass the parent Expression all together, or if not sufficient, then wrap in struct with additional info.

The ultimate idea which solves the #132 as well: hold in Closure not just a BlockInfo stack, but rather whole parent to child stack. The same stack may be used to traverse the expression tree in a loop instead of recursion.

**Comment by jogibear9988** [comment]
I've this for now in #134 by adding a new bool parameter

**Comment by dadhi** [comment]
I see, should work for v2.
