### ISSUE TITLE
Add CI builds on Windows (AppVeyor) and Linux (Travis)

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#26]

**Comment by dadhi** [comment]
Here is the [merged PR](https://github.com/dadhi/FastExpressionCompiler/pull/27) from @iarovyi

**Comment by dadhi** [comment]
Working! Badges are added. Thanks @iarovyi for contribution

**Comment by iarovyi** [comment]
Cool. Looks good.

I wanted to pick up some another simple issue because I'm not mature with MSIL.
As far as I can see the simplest issue is adding Expression.Block (https://github.com/dadhi/FastExpressionCompiler/issues/18)

But I don't understand fully what should be done because as far as I understand Expression.Block does not represent block statements from C# ( { ..... } ). 
And it exists only in order to be a holder for collection of expressions.
So technically Expression.Block is not converted into any MSIL except list of its nested expressions.
At some extend we can say that Block should generate OpCodes.Ret but it is not really true.

Do I understand correctly that in order to convert Expression.Block into MSIL I should just convert its nested expressions?

@dadhi

**Comment by dadhi** [comment]
Interesting observation, I did not know that. Will check.
