### ISSUE TITLE
Async method call

### ISSUE THREAD

**Issue by xxCherry** [dadhi/FastExpressionCompiler#285]
Does it supporting async method call, if yes then please provide minimal example, thanks.

**Comment by dadhi** [comment]
@xxCherry There is no predefined way to express the async method call in System Expression nor in FEC.LightExpression.
Because the `async` is just syntactic sugar over a complex state machine...

But there is a workaround to actually reproduce all this machinery and the MS provides a helper class for this [`ObjectMethodExecutor`](https://github.com/dotnet/aspnetcore/blob/master/src/Shared/ObjectMethodExecutor/ObjectMethodExecutor.cs)

I have the same ObjectMethodExecutor defined in the FEC tests for benchmarking against the System implementation, feel free to grab and experiment with the code (just don't forget the license header):

- Folder with the ObjectMethodExecutor switched to FEC: https://github.com/dadhi/FastExpressionCompiler/tree/master/test/FastExpressionCompiler.IssueTests/ObjectMethodExecutor
- The tests: https://github.com/dadhi/FastExpressionCompiler/blob/master/test/FastExpressionCompiler.IssueTests/Issue72_Try_CompileFast_for_MS_Extensions_ObjectMethodExecutor.cs
- The benchmarks: https://github.com/dadhi/FastExpressionCompiler/blob/master/test/FastExpressionCompiler.Benchmarks/ObjectMethodExecutorBenchmarks.cs
